### ISSUE TITLE
Update the bridge to 0.3.3 in order to add relay mode.

### ISSUE THREAD

**Issue by HansJK** [YunoHost-Apps/mautrix_facebook_ynh#6]
It says in the readme:
>  "Currently the Matrix user can NOT invite other Matrix user in a bridged Facebook room, so only someone with a Facebook account can participate to Facebook group conversations"

But the latest version of the Facebook bridge added support for relay mode. So now you can invite multiple matrix users in a bridged room.

Release: https://github.com/mautrix/facebook/releases/tag/v0.3.3
Issue: https://github.com/mautrix/facebook/issues/13

**Comment by alexAubin** [comment]
Upgraded to 0.4.x in https://github.com/YunoHost-Apps/mautrix_facebook_ynh/pull/12
